In [1]:
import numpy as np
import pandas as pd 
import tensorflow as tf

In [2]:
dataset=pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
Y = dataset.iloc[:,-1].values

In [3]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
Y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [6]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [7]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2,random_state=0)


In [11]:
np.size(X_train)

96000

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [13]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=["accuracy"])

ann.fit(X_train, Y_train, batch_size=32, epochs=100)


Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5894 - accuracy: 0.7159
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4742 - accuracy: 0.7994
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4429 - accuracy: 0.8010
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4284 - accuracy: 0.8043
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4156 - accuracy: 0.8111
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4020 - accuracy: 0.8205
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3891 - accuracy: 0.8314
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3781 - accuracy: 0.8414
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3704 - accuracy: 0.8420
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3659 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3348 - accuracy: 0.8637
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3349 - accuracy: 0.8633
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3346 - accuracy: 0.8635
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3343 - accuracy: 0.8633
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8636
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8654
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8633
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8627
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8634
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3336 - accuracy: 